name: Build Electron App

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        platform: [win32, linux, darwin]
        arch: [x64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Package Electron App
      run: npx electron-packager . MyApp --platform=${{ matrix.platform }} --arch=${{ matrix.arch }} --out=out --overwrite

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MyApp-${{ matrix.platform }}-${{ matrix.arch }}
        path: out/
